# pandas

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy*

**1.** Import pandas under the name `pd`.

In [4]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [5]:
pd.__version__

'2.2.2'

**3.** Print out all the version information of the libraries that are required by the pandas library.

In [6]:
import pandas as pd
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.12.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.6.105+
Version               : #1 SMP Thu Oct  2 10:42:05 UTC 2025
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.4.2
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 6.0.2
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.11
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.0
gcsfs                 : 2025.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.30.0
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.3
sqlalchemy            : 2.0.46
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.12.0
xlrd                  : 2.0.2
zstandard             : 0.25.0
tzdata                : 2025.3
qtpy                  : None
pyqt5                 : None

## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [7]:
import numpy as np
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df=pd.DataFrame(data)
# df

#selecting data
df['animal']
df[['age','visits']]

df.loc[0]
df.iloc[1]

# conditionl selection
df.loc[df['age']>2]

# Sorting data
df.sort_values('age')
df.sort_values(['animal','age'])
df.sort_values('age',ascending=False)

# Adding the data
df['visits']=df['age']*0.10
df.loc[len(df)]=['monkey',2.5,3,'yes']


#aggregating data
df.sum()
df.groupby('animal')['age'].mean()
df.count()
df.min()
df.max()

animal      snake
age           7.0
visits        3.0
priority      yes
dtype: object

**5.** Display a summary of the basic information about this DataFrame and its data.

In [8]:
df.info() #number of rows and columns
# df.head()
# df.tail()
# df.describe()
# df.shape()
# df.dtypes()

<class 'pandas.core.frame.DataFrame'>
Index: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    11 non-null     object
 1   age       9 non-null      float64
 2   visits    9 non-null      float64
 3   priority  11 non-null     object
dtypes: float64(2), object(2)
memory usage: 440.0+ bytes

**6.** Return the first 3 rows of the DataFrame `df`.

In [9]:
data={
    "name":['Jordan','Marie','Kaif','Charlie','Emma'],
    "age":[21,33,55,21,19],
    "country":['USA','UK','UAE','INDIA','SAUDI']
}
df=pd.DataFrame(data)
df

      name  age country
0   Jordan   21     USA
1    Marie   33      UK
2     Kaif   55     UAE
3  Charlie   21   INDIA
4     Emma   19   SAUDI

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [10]:
df=pd.DataFrame(('animal','age'))
df

        0
0  animal
1     age

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [11]:
animal_info={
    "animal":['cat','dog','monkey','tiger','cat','dog','monkey','tiger','dog'],
    'age':[2.5,5,7,11,2.5,5,7,12,3]
}
df=pd.DataFrame(animal_info)
df.loc[(3, 4, 8),['animal','age']]

  animal   age
3  tiger  11.0
4    cat   2.5
8    dog   3.0

**9.** Select only the rows where the number of visits is greater than 3.

In [12]:
import pandas as pd
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

df=pd.DataFrame(data)
# df
# df.loc[df['visits']>=2] # visits not be greater than 3 but put the value is 2
df[df['visits']>2]

  animal  age  visits priority
1    cat  3.0       3      yes
3    dog  NaN       3      yes
5    cat  2.0       3       no

**10.** Select the rows where the age is missing, i.e. is `NaN`.

In [13]:
df.dropna(how='all',axis=1)

  animal  age  visits priority
0    cat  2.5       1      yes
1    cat  3.0       3      yes
2  snake  0.5       2       no
3    dog  NaN       3      yes
4    dog  5.0       2       no
5    cat  2.0       3       no
6  snake  4.5       1       no
7    cat  NaN       1      yes
8    dog  7.0       2       no
9    dog  3.0       1       no

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [14]:
df.loc[(df['animal']=='cat') & (df['age']<3)]

  animal  age  visits priority
0    cat  2.5       1      yes
5    cat  2.0       3       no

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [15]:
df.loc[df['age'].between (2,4)]

  animal  age  visits priority
0    cat  2.5       1      yes
1    cat  3.0       3      yes
5    cat  2.0       3       no
9    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [16]:
df.loc['f','age']=1.5
df

  animal  age  visits priority
0    cat  2.5     1.0      yes
1    cat  3.0     3.0      yes
2  snake  0.5     2.0       no
3    dog  NaN     3.0      yes
4    dog  5.0     2.0       no
5    cat  2.0     3.0       no
6  snake  4.5     1.0       no
7    cat  NaN     1.0      yes
8    dog  7.0     2.0       no
9    dog  3.0     1.0       no
f    NaN  1.5     NaN      NaN

**14.** Calculate the sum of all visits (the total number of visits).

In [17]:
total=df['visits'].sum()
total

np.float64(19.0)

**15.** Calculate the mean age for each different animal in `df`.

In [18]:
res=df.groupby('animal')['age'].mean()
res

animal
cat      2.5
dog      5.0
snake    2.5
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [19]:
df.loc['k']=['dog',3.5,2,'yes']
df=df.drop('k')

**17.** Count the number of each type of animal in `df`.

In [20]:
total=df['animal'].count()
total

np.int64(10)

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visit' column in *ascending* order.

In [21]:
df.sort_values('age',ascending=True) # ascending order for age
df.sort_values('age',ascending=False) # decending order for age

  animal  age  visits priority
8    dog  7.0     2.0       no
4    dog  5.0     2.0       no
6  snake  4.5     1.0       no
9    dog  3.0     1.0       no
1    cat  3.0     3.0      yes
0    cat  2.5     1.0      yes
5    cat  2.0     3.0       no
f    NaN  1.5     NaN      NaN
2  snake  0.5     2.0       no
3    dog  NaN     3.0      yes
7    cat  NaN     1.0      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [22]:
df['priority']=df['priority'].map({'yes':True,'no':False})
df

  animal  age  visits priority
0    cat  2.5     1.0     True
1    cat  3.0     3.0     True
2  snake  0.5     2.0    False
3    dog  NaN     3.0     True
4    dog  5.0     2.0    False
5    cat  2.0     3.0    False
6  snake  4.5     1.0    False
7    cat  NaN     1.0     True
8    dog  7.0     2.0    False
9    dog  3.0     1.0    False
f    NaN  1.5     NaN      NaN

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [23]:

# df=pd.DataFrame(data)
df['animal'].replace('snake','python',inplace=True)

/tmp/ipython-input-1905101647.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['animal'].replace('snake','python',inplace=True)

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (hint: use a pivot table).

In [24]:
import pandas as pd
res=pd.pivot_table(
    df,
    values='age',
    index='animal',
    columns='visits',
    aggfunc='mean'
)
print(res)

visits  1.0  2.0  3.0
animal
cat     2.5  NaN  2.5
dog     3.0  6.0  NaN
python  4.5  0.5  NaN

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

In [25]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df[df['A']!=df['A'].shift(1)]

   A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [26]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df
df.mean()

0    0.792640
1    0.665692
2    0.446787
dtype: float64

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum? (Find that column's label.)

In [27]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
s=df.sum()
# print("sum is",s)
#
m=s.min()
print(" Columns with smallest of sum",m)

 Columns with smallest of sum 1.484770908184288

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)?

In [28]:
d=len(df.drop_duplicates())
print(d)

5

The next three puzzles are slightly harder...

**26.** You have a DataFrame that consists of 10 columns of floating--point numbers. Suppose that exactly 5 entries in each row are NaN values. For each row of the DataFrame, find the *column* which contains the *third* NaN value.

(You should return a Series of column labels.)

In [29]:
import numpy as np
import pandas as pd

np.random.seed(0)
df=pd.DataFrame(np.random.randn(5,10),columns=list('abcdefghij'))

for i in range(len(df)):
  n=np.random.choice(df.columns,5,replace=False)
  df.loc[i,n]=np.nan
  print(n)

  def col(row):
    m=row.isna()

    c=m[m].index
    return c[2]

['c' 'e' 'g' 'd' 'j']
['d' 'j' 'h' 'i' 'g']
['e' 'g' 'd' 'j' 'i']
['j' 'a' 'g' 'e' 'f']
['f' 'a' 'i' 'g' 'h']

**27.** A DataFrame has a column of groups 'grps' and and column of numbers 'vals'. For example:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values.

In [30]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})

# print(df)

df.groupby('grps')['vals'].sum()

grps
a    416
b    160
c    380
Name: vals, dtype: int64

**28.** A DataFrame has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

In [31]:
import pandas as pd
df=pd.DataFrame({
    'A': [3, 7, 12, 18, 25, 33, 47, 58, 64, 79, 85, 92],
    'B': [5, 4, 6, 2, 8, 1, 7, 3, 9, 2, 4, 6]
})
bins=range(0,101,10)
res=df.groupby(pd.cut(df['A'],bins=bins))['B'].sum()
print(res)

A
(0, 10]      9
(10, 20]     8
(20, 30]     8
(30, 40]     1
(40, 50]     7
(50, 60]     3
(60, 70]     9
(70, 80]     2
(80, 90]     4
(90, 100]    6
Name: B, dtype: int64

/tmp/ipython-input-2316238226.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  res=df.groupby(pd.cut(df['A'],bins=bins))['B'].sum()

## DataFrames: harder problems

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be `[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]`. Make this a new column 'Y'.

In [32]:
import pandas as pd
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})

df['Y']=df['X'].eq(0).cumsum()
df['Y']=df.groupby('Y').cumcount()
print(df)

   X  Y
0  7  0
1  2  1
2  0  0
3  3  1
4  4  2
5  2  3
6  5  4
7  0  0
8  3  1
9  4  2

Here's an alternative approach based on a [cookbook recipe](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#grouping):

**30.** Consider a DataFrame containing rows and columns of purely numerical data. Create a list of the row-column index locations of the 3 largest values.

In [33]:
import pandas as pd

df=pd.DataFrame({
    'A':[1,2,3],
    'B':[5,6,7],
    'C':[8,12,10]

})
res=df.stack().nlargest(3).index.tolist()
print(res)

[(1, 'C'), (2, 'C'), (0, 'C')]

**31.** Given a DataFrame with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals', replace any negative values in 'vals' with the group mean.

In [34]:
import pandas as pd
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
res=df['vals']=df['vals'].where(df['vals']>=0,
df.groupby('grps')['vals'].mean())

print(res)

0      12
1     345
2       3
3       1
4      45
5      14
6       4
7      52
8      54
9      23
10    235
11     21
12     57
13      3
14     87
Name: vals, dtype: int64

**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3,
                                 np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

In [35]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'group': list('aabbabbbabab'),
    'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]
})

df['rolling_mean'] = (
    df.groupby('group')['value']
      .rolling(window=3, min_periods=1)
      .mean()
      .reset_index(level=0, drop=True)
)

print(df)

   group  value  rolling_mean
0      a    1.0      1.000000
1      a    2.0      1.500000
2      b    3.0      3.000000
3      b    NaN      3.000000
4      a    2.0      1.666667
5      b    3.0      3.000000
6      b    NaN      3.000000
7      b    1.0      2.000000
8      a    7.0      3.666667
9      b    3.0      2.000000
10     a    NaN      4.500000
11     b    8.0      4.000000

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.

**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [36]:
import numpy as np
import pandas as pd

dates=pd.date_range(start='2015-01-01',end='2015-12-31',freq='B')
# print(dates)

s=pd.Series(np.random.randn(len(dates)),index=dates)

print(s.head())
# print(s.tail())
# print(s.describe())

2015-01-01   -0.206421
2015-01-02    0.488426
2015-01-05   -0.838331
2015-01-06    0.381164
2015-01-07   -0.990903
Freq: B, dtype: float64

**34.** Find the sum of the values in `s` for every Wednesday.

In [37]:
sum=s[s.index.weekday==2].sum()
print(sum)

-6.362600173950585

**35.** For each calendar month in `s`, find the mean of values.

In [38]:
m=s.groupby(s.index.to_period('M')).mean()
print(m.head())

2015-01    0.186096
2015-02    0.229724
2015-03    0.016924
2015-04    0.113172
2015-05   -0.064995
Freq: M, dtype: float64

**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [39]:
res=s.groupby(s.index.to_period('4M')).idxmax()
print(res.head())

2015-01   2015-01-15
2015-02   2015-02-11
2015-03   2015-03-27
2015-04   2015-04-20
2015-05   2015-05-11
Freq: 4M, dtype: datetime64[ns]

**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [40]:
dates=pd.date_range(start="2015-01-01",end="2016-12-31",freq='WOM-3THU')
print(dates)

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
(It's some flight data I made up; it's not meant to be accurate in any way.)

**38.** Some values in the the FlightNumber column are missing. These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Fill in these missing numbers and make the column an integer column (instead of a float column).

In [41]:
import pandas as pd
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
# print(df)
df['FlightNumber']=df['FlightNumber'].interpolate().astype(int)
df

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**39.** The From\_To column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame with the correct values. Assign the correct column names to this temporary DataFrame.

In [42]:
temp=df['From_To'].str.split('_',expand=True)
# print(temp)
temp.columns=['From','To']
print(temp)

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [43]:
temp['From']=temp['From'].str.title()
temp['To']=temp['To'].str.title()

print(temp)

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**41.** Delete the From_To column from `df` and attach the temporary DataFrame from the previous questions.

In [44]:
df=df.drop(columns="From_To").join(temp)
print(df)

   FlightNumber  RecentDelays              Airline      From         To
0         10045      [23, 47]               KLM(!)    London      Paris
1         10055            []    <Air France> (12)    Madrid      Milan
2         10065  [24, 43, 87]  (British Airways. )    London  Stockholm
3         10075          [13]       12. Air France  Budapest      Paris
4         10085      [67, 32]          "Swiss Air"  Brussels     London

**42**. In the Airline column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [45]:
df['Airline']=(df['Airline'].str.replace(r'[^A-Za-z\s]','',regex=True).str.strip())
print(df['Airline'])

0                KLM
1         Air France
2    British Airways
3         Air France
4          Swiss Air
Name: Airline, dtype: object

**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [46]:
delays=pd.DataFrame(df['RecentDelays'].tolist())
# print(delays)
delays.columns=[f'delay_{i+1}' for i in delays.columns]

df=df.drop(columns='RecentDelays').join(delays)
print(df)

   FlightNumber          Airline      From         To  delay_1  delay_2  \
0         10045              KLM    London      Paris     23.0     47.0
1         10055       Air France    Madrid      Milan      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0
3         10075       Air France  Budapest      Paris     13.0      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0

   delay_3
0      NaN
1      NaN
2     87.0
3      NaN
4      NaN

The DataFrame should look much better now.

## Using MultiIndexes

### Go beyond flat DataFrames with additional index levels

Difficulty: *medium*

Previous exercises have seen us analysing data from DataFrames equipped with a single index level. However, pandas also gives you the possibilty of indexing your data using *multiple* levels. This is very much like adding new dimensions to a Series or a DataFrame. For example, a Series is 1D, but by using a MultiIndex with 2 levels we gain of much the same functionality as a 2D DataFrame.

The set of puzzles below explores how you might use multiple index levels to enhance data analysis.

To warm up, we'll look make a Series with two index levels.

**44**. Given the lists `letters = ['A', 'B', 'C']` and `numbers = list(range(10))`, construct a MultiIndex object from the product of the two lists. Use it to index a Series of random numbers. Call this Series `s`.

In [47]:
import numpy as np
import pandas as pd

letter=['A','B','C']
numbers=list(range(10))
# print(numbers)

index=pd.MultiIndex.from_product([letter,numbers],names=['Letter','number'])
s=pd.Series(np.random.randn(len(index)),index=index)
print(s)
# print(s.head())

Letter  number
A       0        -0.804160
        1        -1.198187
        2         0.766769
        3         0.217526
        4         2.084442
        5         1.513476
        6        -2.100825
        7         1.006073
        8        -1.037115
        9        -1.805268
B       0        -1.102196
        1         1.078579
        2        -0.518734
        3        -0.281526
        4         0.560369
        5         0.755209
        6        -1.060891
        7         0.054474
        8        -0.104279
        9        -0.351610
C       0         0.589799
        1        -1.478968
        2        -1.422956
        3        -0.826461
        4         0.784209
        5        -0.195417
        6        -1.264595
        7         0.856933
        8        -0.493994
        9         0.014637
dtype: float64

**45.** Check the index of `s` is lexicographically sorted (this is a necessary proprty for indexing to work correctly with a MultiIndex).

In [48]:

s=s.sort_index()
print(s.head())

Letter  number
A       0        -0.804160
        1        -1.198187
        2         0.766769
        3         0.217526
        4         2.084442
dtype: float64

**46**. Select the labels `1`, `3` and `6` from the second level of the MultiIndexed Series.

In [49]:
i=pd.IndexSlice

res=s.loc[i[:,[1,3,6]]]
print(res)

Letter  number
A       1        -1.198187
        3         0.217526
        6        -2.100825
B       1         1.078579
        3        -0.281526
        6        -1.060891
C       1        -1.478968
        3        -0.826461
        6        -1.264595
dtype: float64

**47**. Slice the Series `s`; slice up to label 'B' for the first level and from label 5 onwards for the second level.

In [50]:
idx=pd.IndexSlice
res=s.loc[idx[:'B',5:]]
print(res)

Letter  number
A       5         1.513476
        6        -2.100825
        7         1.006073
        8        -1.037115
        9        -1.805268
B       5         0.755209
        6        -1.060891
        7         0.054474
        8        -0.104279
        9        -0.351610
dtype: float64

**48**. Sum the values in `s` for each label in the first level (you should have Series giving you a total for labels A, B and C).

In [51]:
s=s.groupby(level=0).sum()
print(s)

Letter
A   -1.357269
B   -0.970604
C   -3.436815
dtype: float64

**49**. Suppose that `sum()` (and other methods) did not accept a `level` keyword argument. How else could you perform the equivalent of `s.sum(level=1)`?

In [52]:

res = df.groupby(s.index.get_level_values(1)).sum()
print(res)

IndexError: Too many levels: Index has only 1 level, not 2

**50**. Exchange the levels of the MultiIndex so we have an index of the form (letters, numbers). Is this new Series properly lexsorted? If not, sort it.

## Minesweeper

### Generate the numbers for safe squares in a Minesweeper grid

Difficulty: *medium* to *hard*

If you've ever used an older version of Windows, there's a good chance you've played with [Minesweeper](https://en.wikipedia.org/wiki/Minesweeper_(video_game). If you're not familiar with the game, imagine a grid of squares: some of these squares conceal a mine. If you click on a mine, you lose instantly. If you click on a safe square, you reveal a number telling you how many mines are found in the squares that are immediately adjacent. The aim of the game is to uncover all squares in the grid that do not contain a mine.

In this section, we'll make a DataFrame that contains the necessary data for a game of Minesweeper: coordinates of the squares, whether the square contains a mine and the number of mines found on adjacent squares.

**51**. Let's suppose we're playing Minesweeper on a 5 by 4 grid, i.e.
```
X = 5
Y = 4
```
To begin, generate a DataFrame `df` with two columns, `'x'` and `'y'` containing every coordinate for this grid. That is, the DataFrame should start:
```
   x  y
0  0  0
1  0  1
2  0  2
```

In [ ]:
import pandas as pd
from itertools import product

X=5
Y=4

coordinates=list(product(range(X),range(Y)))
df=pd.DataFrame(coordinates,columns=['X','Y'])
print(df)

**52**. For this DataFrame `df`, create a new column of zeros (safe) and ones (mine). The probability of a mine occuring at each location should be 0.4.

In [ ]:
import pandas as pd
import numpy as np

m=0.4
df['mine']=np.random.rand(len(df))<m

df['mine']=df['mine'].astype(int)
print(df)

**53**. Now create a new column for this DataFrame called `'adjacent'`. This column should contain the number of mines found on adjacent squares in the grid.

(E.g. for the first row, which is the entry for the coordinate `(0, 0)`, count how many mines are found on the coordinates `(0, 1)`, `(1, 0)` and `(1, 1)`.)

In [ ]:
import pandas as pd

df = pd.DataFrame({
    'x': [0, 0, 0, 1, 1, 1, 2, 2, 2],
    'y': [0, 1, 2, 0, 1, 2, 0, 1, 2],
    'mine': [0, 1, 0, 0, 1, 0, 0, 0, 1]
})
def count_adjacent_mines(row, df):
    x, y = row['x'], row['y']

    neighbors = [(x+dx, y+dy)
                 for dx in [-1, 0, 1]
                 for dy in [-1, 0, 1]
                 if not (dx == 0 and dy == 0)]

    count = df[df[['x','y']].apply(tuple, axis=1).isin(neighbors)]['mine'].sum()
    return count

    df['adjacent'] = df.apply(count_adjacent_mines, axis=1)

print(df)

**54**. For rows of the DataFrame that contain a mine, set the value in the `'adjacent'` column to NaN.

In [ ]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'row': [0, 0, 0, 1, 1, 1, 2, 2, 2],
    'col': [0, 1, 2, 0, 1, 2, 0, 1, 2],
    'mine': [0, 1, 0, 0, 0, 1, 0, 0, 0]
})

def count_adjacent_mines(row):
    r, c = row['row'], row['col']
    adjacent_cells = df[(abs(df['row'] - r) <= 1) & (abs(df['col'] - c) <= 1)]
    return adjacent_cells['mine'].sum() - row['mine']

df['adjacent'] = df.apply(count_adjacent_mines, axis=1)

df.loc[df['mine'] == 1, 'adjacent'] = np.nan
print(df)

**55**. Finally, convert the DataFrame to grid of the adjacent mine counts: columns are the `x` coordinate, rows are the `y` coordinate.

In [ ]:
grid=df.pivot(index='row',columns='col',values='adjacent')
print(grid)

## Plotting

### Visualize trends and patterns in data

Difficulty: *medium*

To really get a good understanding of the data contained in your DataFrame, it is often essential to create plots: if you're lucky, trends and anomalies will jump right out at you. This functionality is baked into pandas and the puzzles below explore some of what's possible with the library.

**56.** Pandas is highly integrated with the plotting library matplotlib, and makes plotting DataFrames very user-friendly! Plotting in a notebook environment usually makes use of the following boilerplate:

```python
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('ggplot')
```

matplotlib is the plotting library which pandas' plotting functionality is built upon, and it is usually aliased to ```plt```.

```%matplotlib inline``` tells the notebook to show plots inline, instead of creating them in a separate window.  

```plt.style.use('ggplot')``` is a style theme that most people find agreeable, based upon the styling of R's ggplot package.

For starters, make a scatter plot of this random data, but use black X's instead of the default markers.

```df = pd.DataFrame({"xs":[1,5,2,8,1], "ys":[4,2,1,9,6]})```

Consult the [documentation](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.plot.html) if you get stuck!

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({"xs":[1,5,2,8,1], "ys":[4,2,1,9,6]})

plt.scatter(df['xs'], df['ys'],color='black',marker='x', s=100)
plt.xlabel('X values')
plt.ylabel('Y values')
plt.title('Scatter plot of random data')
plt.show()

**57.** Columns in your DataFrame can also be used to modify colors and sizes.  Bill has been keeping track of his performance at work over time, as well as how good he was feeling that day, and whether he had a cup of coffee in the morning.  Make a plot which incorporates all four features of this DataFrame.

(Hint:  If you're having trouble seeing the plot, try multiplying the Series which you choose to represent size by 10 or more)

*The chart doesn't have to be pretty: this isn't a course in data viz!*

```
df = pd.DataFrame({"productivity":[5,2,3,1,4,5,6,7,8,3,4,8,9],
                   "hours_in"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
                   "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
                   "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]})
```

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

# Data
df = pd.DataFrame({
    "productivity":[5,2,3,1,4,5,6,7,8,3,4,8,9],
    "hours_in"    :[1,9,6,5,3,9,2,9,1,7,4,2,2],
    "happiness"   :[2,1,3,2,3,1,2,3,1,2,2,1,3],
    "caffienated" :[0,0,1,1,0,0,0,0,1,1,0,1,0]
})

plt.figure(figsize=(8,6))
scatter = plt.scatter(
    x=df['hours_in'],
    y=df['productivity'],
    c=df['happiness'],
    s=(df['caffienated'] + 1)*100,
    cmap='viridis',
    alpha=0.7,
    edgecolors='black'
)

plt.xlabel('Hours Worked')
plt.ylabel('Productivity')
plt.title('Productivity vs Hours Worked, Colored by Happiness, Sized by Coffee')


cbar = plt.colorbar(scatter)
cbar.set_label('Happiness Level')

plt.show()

**58.**  What if we want to plot multiple things?  Pandas allows you to pass in a matplotlib *Axis* object for plots, and plots will also return an Axis object.

Make a bar plot of monthly revenue with a line plot of monthly advertising spending (numbers in millions)

```
df = pd.DataFrame({"revenue":[57,68,63,71,72,90,80,62,59,51,47,52],
                   "advertising":[2.1,1.9,2.7,3.0,3.6,3.2,2.7,2.4,1.8,1.6,1.3,1.9],
                   "month":range(12)
                  })
```

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

df = pd.DataFrame({"revenue":[57,68,63,71,72,90,80,62,59,51,47,52],
                   "advertising":[2.1,1.9,2.7,3.0,3.6,3.2,2.7,2.4,1.8,1.6,1.3,1.9],
                   "month":range(12)
                  })
# print(df)
fig,ax=plt.subplots(figsize=(10,5))

df.plot(kind='bar', x='month', y='revenue', ax=ax, color='skyblue', label='Revenue (M)')


df.plot(kind='line', x='month', y='advertising', ax=ax, color='red', marker='o', label='Advertising (M)', secondary_y=False)


ax.set_xlabel('Month')
ax.set_ylabel('Revenue (Millions)')
ax.set_title('Monthly Revenue and Advertising Spending')

ax2 = ax.twinx()
df.plot(kind='line', x='month', y='advertising', ax=ax2, color='red', marker='o', label='Advertising (M)')
ax2.set_ylabel('Advertising (Millions)')


plt.show()

Now we're finally ready to create a candlestick chart, which is a very common tool used to analyze stock price data.  A candlestick chart shows the opening, closing, highest, and lowest price for a stock during a time window.  The color of the "candle" (the thick part of the bar) is green if the stock closed above its opening price, or red if below.

![Candlestick Example](img/candle.jpg)

This was initially designed to be a pandas plotting challenge, but it just so happens that this type of plot is just not feasible using pandas' methods.  If you are unfamiliar with matplotlib, we have provided a function that will plot the chart for you so long as you can use pandas to get the data into the correct format.

Your first step should be to get the data in the correct format using pandas' time-series grouping function.  We would like each candle to represent an hour's worth of data.  You can write your own aggregation function which returns the open/high/low/close, but pandas has a built-in which also does this.

The below cell contains helper functions.  Call ```day_stock_data()``` to generate a DataFrame containing the prices a hypothetical stock sold for, and the time the sale occurred.  Call ```plot_candlestick(df)``` on your properly aggregated and formatted stock data to print the candlestick chart.

In [ ]:
import numpy as np
def float_to_time(x):
    return str(int(x)) + ":" + str(int(x%1 * 60)).zfill(2) + ":" + str(int(x*60 % 1 * 60)).zfill(2)

def day_stock_data():
    #NYSE is open from 9:30 to 4:00
    time = 9.5
    price = 100
    results = [(float_to_time(time), price)]
    while time < 16:
        elapsed = np.random.exponential(.001)
        time += elapsed
        if time > 16:
            break
        price_diff = np.random.uniform(.999, 1.001)
        price *= price_diff
        results.append((float_to_time(time), price))


    df = pd.DataFrame(results, columns = ['time','price'])
    df.time = pd.to_datetime(df.time)
    return df

#Don't read me unless you get stuck!
def plot_candlestick(agg):
    """
    agg is a DataFrame which has a DatetimeIndex and five columns: ["open","high","low","close","color"]
    """
    fig, ax = plt.subplots()
    for time in agg.index:
        ax.plot([time.hour] * 2, agg.loc[time, ["high","low"]].values, color = "black")
        ax.plot([time.hour] * 2, agg.loc[time, ["open","close"]].values, color = agg.loc[time, "color"], linewidth = 10)

    ax.set_xlim((8,16))
    ax.set_ylabel("Price")
    ax.set_xlabel("Hour")
    ax.set_title("OHLC of Stock Value During Trading Day")
    plt.show()

**59.** Generate a day's worth of random stock data, and aggregate / reformat it so that it has hourly summaries of the opening, highest, lowest, and closing prices

In [53]:
import pandas as pd
import numpy as np

date = "2026-02-02"
minutes = pd.date_range(start=f"{date} 09:30", end=f"{date} 16:00", freq='T')


np.random.seed(42)
price = 100 + np.cumsum(np.random.randn(len(minutes)) * 0.5)

df = pd.DataFrame({'price': price}, index=minutes)
hourly = df['price'].resample('H').ohlc()

print(hourly)

                           open        high         low       close
2026-02-02 09:00:00  100.248357  102.240306   97.177797   97.177797
2026-02-02 10:00:00   96.876943   97.803082   93.876672   95.553631
2026-02-02 11:00:00   95.602170   96.579807   93.236527   93.825485
2026-02-02 12:00:00   93.950731   98.991169   93.689431   98.991169
2026-02-02 13:00:00   99.276614  101.319706   97.494864   97.560234
2026-02-02 14:00:00   98.280871  103.395955   97.531601  103.395955
2026-02-02 15:00:00  103.389832  105.177395   99.972250  103.720218
2026-02-02 16:00:00  103.271010  103.271010  103.271010  103.271010

/tmp/ipython-input-722034461.py:5: FutureWarning: 'T' is deprecated and will be removed in a future version, please use 'min' instead.
  minutes = pd.date_range(start=f"{date} 09:30", end=f"{date} 16:00", freq='T')
/tmp/ipython-input-722034461.py:12: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hourly = df['price'].resample('H').ohlc()

**60.** Now that you have your properly-formatted data, try to plot it yourself as a candlestick chart.  Use the ```plot_candlestick(df)``` function above, or matplotlib's [```plot``` documentation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.plot.html) if you get stuck.

In [58]:
import matplotlib.pyplot as plt
import pandas as pd

def plot_candlestick(df):
    fig, ax = plt.subplots(figsize=(10, 6))
    x = range(len(df))

    for i, (open_, high, low, close) in enumerate(
        zip(df['open'], df['high'], df['low'], df['close'])
    ):

        ax.plot([i, i], [low, high])
        if close >= open_:
            ax.plot([i, i], [open_, close], linewidth=6)
        else:
            ax.plot([i, i], [close, open_], linewidth=6)


    ax.set_xticks(x)
    ax.set_xticklabels(df.index.strftime('%H:%M'), rotation=45)

    ax.set_title("Candlestick Chart")
    ax.set_ylabel("Price")
    ax.set_xlabel("Time")

    plt.tight_layout()
    plt.show()